# Generated by Django 3.1.4 on 2021-01-11 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='new_email',
            field=models.CharField(default='new_net@gmail.com', max_length=100),
        ),
    ]
