# Generated by Django 3.1.3 on 2020-12-28 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkApp', '0002_position_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='storage',
            field=models.CharField(default='0', max_length=10, null=True),
        ),
    ]
