# Generated by Django 3.1.4 on 2021-01-08 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkApp', '0005_operationlist_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='coatingplace',
            name='identification',
            field=models.CharField(default='coa', max_length=50),
        ),
        migrations.AddField(
            model_name='cuttingplace',
            name='identification',
            field=models.CharField(default='cut', max_length=50),
        ),
        migrations.AddField(
            model_name='machiningplace',
            name='identification',
            field=models.CharField(default='mach', max_length=50),
        ),
        migrations.AddField(
            model_name='otherplace',
            name='identification',
            field=models.CharField(default='oth', max_length=50),
        ),
    ]
